'''
#this program is to show that and error can be generated by self with help of raise module

cpu_usage = int(input("Enter the CPU usage here! : "))

if cpu_usage < 0 or cpu_usage > 100:
    raise ValueError("CPU usage must be between 0 and 100")

print(f"CPU usage is: {cpu_usage}%")

'''

try:
    cpu_usage = int(input("enter the cpu usage value here: "))

    if cpu_usage < 0 or cpu_usage > 100:
        raise ValueError("CPU Usage value must be between 0 and 100")

    print(f"CPU usage is {cpu_usage}%")

except ValueError as error:
    print(f"Error: {error}")

print("Program Complete.")